### ISSUE TITLE
Build/run WRF in container using intel compiler

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/i-wrf#40]
David Hahn has experience using Intel compilers.

## Describe the Task ##
Create a dockerfile and build script to create an image with WPS and WRF.
- [x] Use ubuntu:22.04 as base image
- [x] Install Intel compilers
- [x] Add user _wrfuser_ with uid=5000
- [x] Update /etc/bashrc to configure paths and compiler environment
- [x] Update /etc/security/limits.conf to allow unlimited stack space for all users (necessary to run WRF)
- [x] Download software dependencies:
    - [x] CMake 3.25
    - [x] ECCodes 2.27.0
    - [x] g2clib 1.6.0
    - [x] jasper 1.900.29
    - [x] hdf5 1.10.10
    - [x] libaec 1.0.6
    - [x] libpng 1.2.50
    - [x] ncview 2.1.7
    - [x] netcdf 4.7.3
    - [x] netcdf-cxx 4.3.1
    - [x] netcdf-fortran 4.5.2
    - [x] szip 2.1.1
    - [x] zlib 1.2.11
    - [x] udunits 2.2.28
- [x] Create patches to allow WPS v4.4 and Jasper 1.900.29 with latest compilers
- [x] Compile the above software dependencies
- [x] Compile WRF 4.3.3
- [x] Compile WPS 4.4
- [x] Add steps to check error codes of library builds
- [x] Add steps to check for expected WRF and WPS files from the build
- [x] Add a WPS patch to fix errors with the icx compiler from Intel oneAPI
- [ ] Add WRF/WPS versions into the documentation

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
None

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Task Checklist ##
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
20230707 - decided to use ubuntu 22.04 as base image

**Comment by georgemccabe** [comment]
@hahnd, to wrap up this issue:

- [ ] Build the latest WRF container and push it to DockerHub ncar/iwrf
- [ ] Create a pull request to merge these changes into main

Please add any other action items needed before closing this issue.

**Comment by hahnd** [comment]
The latest WPS (v4.6.0) does not compile with the Intel oneAPI compilers.  See [WPS#245](https://github.com/wrf-model/WPS/pull/245) for details.  The next WPS release should include the fix and we will update this branch to the latest WPS version before creating a PR.

**Comment by georgemccabe** [comment]
@hahnd, could you provide an update on this issue? Is this ready to merge?

**Comment by hahnd** [comment]
@georgemccabe - There is more work to do on the docker images and documentation.  Last week we decided we want to make sure that the LULC (older WRF and WPS versions) are running on multiple nodes on redcloud.  So, if we close this issue, we need to open a new one for that.  The scope of this issue has certainly grown quite large.

**Comment by jaredalee** [comment]
@hahnd Could you please provide an update here on what you did for the WPS/WRF docker images for the LULC use case (subtask of #31)? If that's all done, can we close the issue, or is there anything more left to be done?

**Comment by hahnd** [comment]
The #40 feature branch has two subdirectories under the [`docker` directory](https://github.com/NCAR/i-wrf/tree/feature/40-build-wrf-container/docker): one for LULC and one for I-WRF.

The LULC docker scripts build WRF 4.3.3 and WPS 4.4.
The I-WRF docker scripts build WRF 4.5.2 and WPS develop.

The WPS develop branch builds with the latest Intel compilers.  Not sure if WPS developers ever released a version to support this.  We could check with @islas.  It would be good to put a fixed version number in there before merging this branch.

**Comment by jaredalee** [comment]
@islas Do you have any updates on when an official WPS release will support compiling with intel oneAPI compilers? It seems like that's the hold-up for us right now, at least for this particular issue.

**Comment by islas** [comment]
WPS compiles with the Intel OneAPI compilers in the latest release. This PR (https://github.com/wrf-model/WPS/pull/250) adds the appropriate stanza configuration to select

**Comment by hahnd** [comment]
@islas - we have been using the 'develop' branch to build for a while.  Has this feature been merged into any official release yet?  Maybe 4.6.0?

**Comment by islas** [comment]
@hahnd Yes, sorry I should have specified. The above PR was the official fix which was part of the latest v4.6.0. I cited the PR as reference to the actual changes rather than the full release.

**Comment by hahnd** [comment]
Thanks!  I'll make this change and rebuild the image.

**Comment by hahnd** [comment]
This image built successfully yesterday.  I pushed it to docker hub to make it available for testing: ncar/iwrf:20241203
