### ISSUE TITLE
Update METplus use case to use madis2nc wrapper when it is available

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/i-wrf#51]
The madis2nc wrapper has not yet been created (issue dtcenter/METplus#1514). The METplus use case (#48) can still call the madis2nc MET tool by using the UserScript wrapper.

## Describe the Task ##
When the madis2nc wrapper is available, update the METplus use case to call the wrapper instead of UserScript.

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
I-WRF 1.0.0 (not required for 0.1.0)

### Funding Source ###
I-WRF 7790013

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Task Checklist ##
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Note that the madis2nc wrapper was added to METplus for the v6.0.0 release in December 2024.

Changed the project board status for this issue from Pending to Ready since the required METplus functionality does now exist.

**Comment by georgemccabe** [comment]
The Hurricane Matthew use case has been using the MADIS2NC METplus wrapper since it was added in PR #53. This issue can be closed.
