### ISSUE TITLE
Update the Hurricane Matthew use-case once dtcenter/MET#1518 is completed in MET-12.0.0-beta5

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/i-wrf#52]
## Describe the Enhancement ##
dtcenter/MET#1518 will generalize support for the handling of winds in MET. This functionality is needed for the i-wrf to rotate the U and V wind components from grid-to-earth relative prior to verifying them.

This issue is to track the completion of dtcenter/MET#1518 as well as any corresponding dtcenter/METplus issues to make it configurable through METplus. Once those feature(s) are added in the METplus-6.0.0-beta5 coordinated release, update the Hurricane Matthew use case to call it.

### Time Estimate ###
1 day, once the functionality has been added to METplus.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
7790013

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Enhancement Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Note that this work is also needed for the i-wrf project (https://github.com/NCAR/i-wrf/issues/52) and should be prioritized.

**Comment by JohnHalleyGotway** [comment]
Discussed on July 24, 2026. Plan to do this work after the METplus-13.0.0 release in September. This work includes:
- Updating the MET version number used for I-WRF to METplus-13.0.0.
- Test to confirm that U10 and V10 are properly rotated from grid-to-earth relative prior to being verified in Point-Stat.
- Update the use case configuration, if needed, to enable the rotation.
- Recommend noting the output values before/after this change to see the impact of properly rotating the winds.

**Comment by JohnHalleyGotway** [comment]
As discussed again on Sept 4, 2026, the plan for this work remains the same. This work is dependent on the METplus-13.0 release, which has been delayed due to funding issues.
