### ISSUE TITLE
Add namelist.wps from the container to Github

### ISSUE THREAD

**Issue by jaredalee** [NCAR/i-wrf#58]
## Describe the Task ##
Add the WPS namelist (namelist.wps) file that is currently being used in the WRF container under development, to the use_cases/Hurricane_Matthew/WRF folder in the Github repo. This file should already have the container-relative file locations specified for geog_data_path, opt_geogrid_tbl_path, prefix, fname, and opt_metgrid_tbl_path. Then this namelist can be downloaded from the repository unmodified to support running the Hurricane Matthew test case. Once it has been uploaded to the repo, then Sec. 4.1.1.1 of the readthedocs should be updated accordingly to point directly to this file.

### Time Estimate ###
Less than 1 hour.

### Sub-Issues ###
- [ ] Upload namelist.wps to use_cases/Hurricane_Matthew/WRF. (Bennett)
- [ ] Update documentation in Sec. 4.1.1.1 to link to this namelist.wps. (Jared)

### Relevant Deadlines ###
12 Jul 2024

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jaredalee** [comment]
@Trumbore, I initially assigned this to @rcplane, but it's also something you could take care of quickly. By uploading your modified namelist.wps to here, then you could adjust the run script to simply download namelist.wps from the repository, rather than modifying it locally. Similarly, the WRF namelist (namelist.input), which I just updated and committed per our meeting this morning, can be directly downloaded from the repo instead of doing any local modification of the file. That would make for a cleaner run script.

**Comment by jaredalee** [comment]
Closing this issue as having been resolved by #56.
