### ISSUE TITLE
Add script(s) to run Hurricane Matthew WRF & METPlus containers to new scripts directory

### ISSUE THREAD

**Issue by jaredalee** [NCAR/i-wrf#59]
## Describe the Task ##
Add a use_cases/Hurricane_Matthew/scripts directory, and in that directory add any script(s) that are needed to run the WRF & METPlus containers for the Hurricane Matthew case on Jetstream2. Also add accompanying documentation to readthedocs. If modified script(s) are needed for Derecho or other platforms, then we'll also add them to that directory and add accompanying documentation.

### Time Estimate ###
Should be about a day for remaining modifications.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] Upload the run script for the WRF container
- [ ] Upload the run script for the METPlus container (if separate)
- [ ] Add documentation to readthedocs

### Relevant Deadlines ###
19 Jul 2024

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jaredalee** [comment]
It seems this issue can be safely closed as having been resolved by #49 via PR #56.
